config/routes.rb
require 'resque/server'

Kochiku::Application.routes.draw do
  mount Resque::Server.new, :at => '/resque'

  if Rails.env.development?
    # https://github.com/rails/rails/pull/17896
    get '/rails/mailers' => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
  end

  root :to => "repositories#dashboard"

  get '/_status' => "status#available"

  # /repositories/1/build-ref?ref=master&sha=abc123
  resources :repositories, only: [:index, :create, :new, :update, :destroy] do
    member do
      post "build-ref", :action => 'build_ref', :as => 'build_ref'
    end
  end

  match '/XmlStatusReport.aspx', to: "branches#status_report", defaults: {:format => 'xml'}, via: :get
  match '/worker_health', to: "dashboards#build_history_by_worker", via: :get, as: :build_history_by_worker

  match 'builds/:id' => "builds#build_redirect", :via => :get, :as => :build_redirect, :id => /\d+/
  match 'builds/:id/status' => "builds#build_status", :via => :get, :as => :build_status, :id => /\d+/, :defaults => { :format => 'json' }
  match 'builds/:ref' => "builds#build_ref_redirect", :via => :get, :as => :build_ref_redirect
  match '/build_attempts/:build_attempt_id/build_artifacts' => "build_artifacts#create", :via => :post
  match '/build_attempts/:id/start' => "build_attempts#start", :via => :post
  match '/build_attempts/:id/finish' => "build_attempts#finish", :via => :post, :as => :finish_build_attempt
  # left here for backward compatibility in case if anyone uses it. /build_attempts/:id should be used instead.
  match '/build_attempts/:id/build_part' => "build_attempts#show", :via => :get, :as => :build_part_redirect
  match '/build_attempts/:id/stream_logs' => "build_attempts#stream_logs", :via => :get, :as => :stream_logs
  match '/build_attempts/:id/stream_logs_chunk' => "build_attempts#stream_logs_chunk", :via => :get, :as => :stream_logs_chunk
  match '/pull-request-builder' => "pull_requests#build", :via => :post, :as => :pull_request_build
  get 'badge/*repository_path', to: 'branches#badge'

  # Redirects for legacy urls
  get '/projects/:project_id/builds/:build_id', to: redirect('/builds/%{build_id}')

  resources :build_artifacts, :only => [:show]
  resources :builds, only: [:create]
  resources :build_attempts, only: [:show]

  scope path: "*repository_path", as: 'repository', constraints: { repository_path: /[^\/]+\/[^\/]+/ }, format: false do
    get 'edit', to: 'repositories#edit'

    resources :builds, only: [:show] do
      post 'toggle-merge-on-success', :action => "toggle_merge_on_success", :on => :member, :as => :toggle_merge_on_success
      patch 'abort', :action => "abort", :on => :member
      get 'status', :action => "build_status", :on => :member, :defaults => { :format => 'json' }
      post 'rebuild-failed-parts', :action => "rebuild_failed_parts", :on => :member, :as => :rebuild_failed_parts
      post 'retry-partitioning', :action => "retry_partitioning", :on => :member, :as => :retry_partitioning
      get 'modified_time', :action => "modified_time", :on => :member, :defaults => { :format => 'json' }
      get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      post 'resend-status', :action => "resend_status",  :on => :member, :defaults => { :format => 'json' }

      resources :build_parts, as: 'parts', path: 'parts', only: [:show] do
        post 'rebuild', on: :member
        get 'modified_time', action: "modified_time", on: :member, defaults: { format: 'json' }
        get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      end
    end

    # override branch id to allow branch name to contain both slashes and dots
    resources :branches, path: "", only: [:index, :show], constraints: { id: /.+/ } do
      member do
        post 'request-new-build', action: "request_new_build"
        get 'build-time-history', action: "build_time_history", defaults: { format: 'json' }
        get 'health', action: 'health'
      end
      get 'status-report', action: "status_report", on: :collection
    end
  end
end

app/models/build_part.rb
class BuildPart < ActiveRecord::Base
  # using 'build_instance' instead of 'build' because AR defines `build` for associations, and it wins
  belongs_to :build_instance, :class_name => "Build", :foreign_key => "build_id", :inverse_of => :build_parts
  has_many :build_attempts, :dependent => :destroy, :inverse_of => :build_part
  validates :kind, :paths, :queue, presence: true

  serialize :paths, Array
  serialize :options, Hash

  def last_attempt
    build_attempts.last
  end

  def create_and_enqueue_new_build_attempt!
    build_attempt = build_attempts.create!(:state => 'runnable')
    BuildAttemptJob.enqueue_on(queue.to_s, job_args(build_attempt))
    build_instance.touch # invalidate the cache of builds#show
    build_attempt
  rescue GitRepo::RefNotFoundError
    # delete the dud build_attempt and re-raise
    build_attempt.destroy if build_attempt

    raise
  end
  alias rebuild! create_and_enqueue_new_build_attempt!

  def job_args(build_attempt)
    repository = build_instance.repository
    {
      "build_attempt_id" => build_attempt.id,
      "build_kind" => kind,
      "build_ref" => build_instance.ref,
      "branch" => build_instance.branch_record.name,
      "test_files" => paths,
      "repo_name" => "#{repository.name}-cache",  # need to pass -cache for now for compatibility with current kochiku-worker
      "test_command" => build_instance.test_command,
      "repo_url" => repository.url_for_fetching,
      "remote_name" => "origin",
      "timeout" => repository.timeout.minutes,
      "options" => options,
      "kochiku_env" => Rails.env,
    }
  end

  def status
    if successful?
      'passed'
    else
      last_attempt.try(:state) || 'unknown'
    end
  end

  def successful?
    build_attempts.any?(&:successful?)
  end

  def unsuccessful?
    !successful?
  end

  def running?
    started_at && !finished_at
  end

  def not_finished?
    !finished_at
  end

  def to_color
    case status
    when 'passed'
      :green
    when 'failed', 'errored', 'aborted'
      :red
    else
      :blue
    end
  end

  def started_at
    last_attempt.try(:started_at)
  end

  def finished_at
    last_attempt.try(:finished_at)
  end

  def elapsed_time
    if finished_at && started_at
      finished_at - started_at
    elsif started_at
      Time.current - started_at
    end
  end

  def as_json(options = {})
    super(options.reverse_merge(methods: :status))
  end

  def should_reattempt?
    if successful?
      false
    elsif (build_attempts.unsuccessful.count - 1) < retry_count
      true
    # automatically retry build parts that errored in less than 60 seconds
    elsif elapsed_time && elapsed_time < 60 && last_attempt.errored? &&
          build_attempts.unsuccessful.count < 5
      true
    else
      false
    end
  end
end

app/controllers/build_parts_controller.rb
class BuildPartsController < ApplicationController
  before_action :load_repository_build_and_part, only: [:rebuild, :show, :modified_time, :refresh_build_part_info]
  before_action only: [:show, :refresh_build_part_info] do
    calculate_build_attempts_position(@build_part.build_attempts, @build_part.queue)
  end

  include BuildAttemptsQueuePosition

  caches_action :show, cache_path: proc {
    {
      modified: [@build_part.updated_at.to_i, @repository.updated_at.to_i].max,
      queue_position: Digest::SHA1.hexdigest(@build_attempts_rank.values.join(','))
    }
  }

  def show
    respond_to do |format|
      format.html
      format.json do
        render :json => @build_part, include: { build_attempts: { methods: :files } }
      end
    end
  end

  def rebuild
    begin
      @build_part.rebuild!
    rescue GitRepo::RefNotFoundError
      flash[:error] = "It appears the commit #{@build.ref} no longer exists."
    end

    redirect_to [@repository, @build]
  end

  def modified_time
    respond_to do |format|
      format.json do
        render :json => @build_part.updated_at
      end
    end
  end

  def refresh_build_part_info
    updates = []
    if @build_part.finished_at
      updates << { state: @build_part.status }
    else
      @build_part.build_attempts.each_with_index do |attempt, index|
        html = ApplicationController.render(partial: 'build_parts/build_attempts', locals: {  index: index,
                                                                                              attempt: attempt,
                                                                                              build_attempts_rank: @build_attempts_rank})
        updates << {id: index, content: html, state: @build_part.status}
      end
    end
    respond_to do |format|
      format.json do
        render :json => updates
      end
    end
  end

  private

  def load_repository_build_and_part
    r_namespace, r_name = params[:repository_path].split('/')
    @repository = Repository.where(namespace: r_namespace, name: r_name).first!
    @build = Build.joins(:branch_record).where('branches.repository_id' => @repository.id).find(params[:build_id])
    @build_part = @build.build_parts.find(params[:id])
  end
end

app/helpers/build_parts_helper.rb
module BuildPartsHelper
  def basename_with_extension(path)
    File.basename(path)
  end

  def basename_without_extension(path)
    File.basename(path, File.extname(path))
  end
end

app/views/build_parts/_build_attempts.html.haml
%tr{id: dom_id(attempt), :"data-id" => index + 1}
  %td.right= link_to(index + 1, attempt)
  %td
    %span.attempt-status{:class => attempt.state}= attempt.state.to_s.capitalize
  %td.rank= build_attempts_rank[attempt.id.to_s]
  %td= attempt.started_at
  %td.right.elapsed= duration_strftime(attempt.elapsed_time)
  %td.right= attempt.builder ? attempt.builder.sub(".#{Settings.domain_name}", '') : "pending"
  %td
    - if attempt.running? && attempt.log_streamer_port.present?
      = link_to("stdout.log (in progress)", stream_logs_path(attempt.id))
    - else
      - attempt.build_artifacts.sort_by { |artifact| artifact.log_file.path }.each do |artifact|
        = link_to File.basename(artifact.log_file.path), artifact
        %br
  %td.wrap
    - unless attempt.stopped?
      = link_to("Abandon", finish_build_attempt_path(attempt, :state => 'aborted'), :method => :post)

app/views/build_parts/_build_part.html.haml
.part{:class => build_part.status, :title => build_part.paths.map{|path| "-#{path}"}.join("<br>")}
  -# build_part.build_instance.repository is important to prevent n+1 queries here. Using the :through does a bunch of SQL.
  %a.part-wrapper{:href => repository_build_part_path(build_part.build_instance.repository, build_part.build_instance, build_part)}
    .kind
      - case build_part.kind
      - when "spec"
        Specs
      - when "cucumber"
        Cukes
      - else
        = build_part.kind
    - if build_part.build_attempts.any?
      .attempts
        = render build_part.last_attempt
        - if build_part.build_attempts.size > 1
          = "..."

app/views/build_parts/show.html.haml
= content_for :title do
  = @build.ref[0, 7]
  &ndash;
  = @repository.name
= content_for :favicon do
  = favicon_link_tag image_path("#{@build_part.to_color}.png"), :type => 'image/png'

%h2.subheader
  = link_to(@build.repository.name_with_namespace, repository_branches_path(@build.repository))
  &ndash;
  = link_to(@build.branch_record.name, repository_branch_path(@build.repository, @build.branch_record))
  &ndash;
  = link_to repository_build_path(@repository, @build) do
    %code.build-status{class: @build.state, title: @build.ref}
      = @build.ref[0, 7]
  &ndash; #{@build_part.kind} (part #{@build_part.id})

  .actions
    %label
      - if @repository.enabled?
        = link_to("Rebuild", rebuild_repository_build_part_path(@repository, @build, @build_part), method: :post, class: "rebuild button")
    %label
      = check_box_tag :refresh, true, @build_part.not_finished?
      Refresh

.build-info.build-info-subheader
  %span.info
    %span.status{:class => 'build-part-' + @build_part.status.to_s}= @build_part.status.to_s.capitalize
    on
    %span.queue #{@build_part.queue} queue

%table.build-part-info
  %thead
    %tr
      %th.right.count Attempt
      %th.status Status
      %th.queue-position Position
      %th Started At
      %th.right.time Elapsed Time
      %th.right.worker Worker
      %th Build Artifacts
      %th.right.actions Actions
  %tbody
    - @build_part.build_attempts.each_with_index do |attempt, index|
      = render partial: 'build_parts/build_attempts', locals: {attempt: attempt, index: index, build_attempts_rank: @build_attempts_rank}

%ol#build-paths
  - if @build_part.options['total_workers'] && @build_part.options['worker_chunk']
    %li Chunk #{@build_part.options['worker_chunk']} of #{@build_part.options['total_workers']}
  - @build_part.paths.each do |path|
    %li= path

= content_for :javascript do
  :javascript
    if ($('.build-part-info tbody tr').length > 0) {
      $('.build-part-info').tablesorter({ sortList: [ [0, 0] ] });
      StartTimes = #{
        # rubocop:disable Style/IndentationConsistency
        start_times = {}
        @build_part.build_attempts.each_with_index { |attempt, index| start_times[index + 1] = attempt.started_at }
        start_times.to_json
      };
    }

    if ( "Notification" in window && Notification.permission == "default") {
      Notification.requestPermission();
    }

    Kochiku.buildInfo = {table: '.build-part-info tbody', renderTime: Date.parse("#{raw @build_part.updated_at}"), state: "#{@build.state}"};

    Kochiku.buildInfo.id = #{@build.id};
    Kochiku.buildInfo.branch = "#{@build.branch_record.name}";
    Kochiku.buildInfo.repo = "#{@build.repository.name}";

    Kochiku.terminalStates = #{raw BuildAttempt::COMPLETED_BUILD_STATES};
    Kochiku.doneMessage = "BuildPart on "

    Kochiku.delayedRefresh(Kochiku.buildInfo);