config/routes.rb
require 'resque/server'

Kochiku::Application.routes.draw do
  mount Resque::Server.new, :at => '/resque'

  if Rails.env.development?
    # https://github.com/rails/rails/pull/17896
    get '/rails/mailers' => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
  end

  root :to => "repositories#dashboard"

  get '/_status' => "status#available"

  # /repositories/1/build-ref?ref=master&sha=abc123
  resources :repositories, only: [:index, :create, :new, :update, :destroy] do
    member do
      post "build-ref", :action => 'build_ref', :as => 'build_ref'
    end
  end

  match '/XmlStatusReport.aspx', to: "branches#status_report", defaults: {:format => 'xml'}, via: :get
  match '/worker_health', to: "dashboards#build_history_by_worker", via: :get, as: :build_history_by_worker

  match 'builds/:id' => "builds#build_redirect", :via => :get, :as => :build_redirect, :id => /\d+/
  match 'builds/:id/status' => "builds#build_status", :via => :get, :as => :build_status, :id => /\d+/, :defaults => { :format => 'json' }
  match 'builds/:ref' => "builds#build_ref_redirect", :via => :get, :as => :build_ref_redirect
  match '/build_attempts/:build_attempt_id/build_artifacts' => "build_artifacts#create", :via => :post
  match '/build_attempts/:id/start' => "build_attempts#start", :via => :post
  match '/build_attempts/:id/finish' => "build_attempts#finish", :via => :post, :as => :finish_build_attempt
  # left here for backward compatibility in case if anyone uses it. /build_attempts/:id should be used instead.
  match '/build_attempts/:id/build_part' => "build_attempts#show", :via => :get, :as => :build_part_redirect
  match '/build_attempts/:id/stream_logs' => "build_attempts#stream_logs", :via => :get, :as => :stream_logs
  match '/build_attempts/:id/stream_logs_chunk' => "build_attempts#stream_logs_chunk", :via => :get, :as => :stream_logs_chunk
  match '/pull-request-builder' => "pull_requests#build", :via => :post, :as => :pull_request_build
  get 'badge/*repository_path', to: 'branches#badge'

  # Redirects for legacy urls
  get '/projects/:project_id/builds/:build_id', to: redirect('/builds/%{build_id}')

  resources :build_artifacts, :only => [:show]
  resources :builds, only: [:create]
  resources :build_attempts, only: [:show]

  scope path: "*repository_path", as: 'repository', constraints: { repository_path: /[^\/]+\/[^\/]+/ }, format: false do
    get 'edit', to: 'repositories#edit'

    resources :builds, only: [:show] do
      post 'toggle-merge-on-success', :action => "toggle_merge_on_success", :on => :member, :as => :toggle_merge_on_success
      patch 'abort', :action => "abort", :on => :member
      get 'status', :action => "build_status", :on => :member, :defaults => { :format => 'json' }
      post 'rebuild-failed-parts', :action => "rebuild_failed_parts", :on => :member, :as => :rebuild_failed_parts
      post 'retry-partitioning', :action => "retry_partitioning", :on => :member, :as => :retry_partitioning
      get 'modified_time', :action => "modified_time", :on => :member, :defaults => { :format => 'json' }
      get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      post 'resend-status', :action => "resend_status",  :on => :member, :defaults => { :format => 'json' }

      resources :build_parts, as: 'parts', path: 'parts', only: [:show] do
        post 'rebuild', on: :member
        get 'modified_time', action: "modified_time", on: :member, defaults: { format: 'json' }
        get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      end
    end

    # override branch id to allow branch name to contain both slashes and dots
    resources :branches, path: "", only: [:index, :show], constraints: { id: /.+/ } do
      member do
        post 'request-new-build', action: "request_new_build"
        get 'build-time-history', action: "build_time_history", defaults: { format: 'json' }
        get 'health', action: 'health'
      end
      get 'status-report', action: "status_report", on: :collection
    end
  end
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :repository
  has_many :builds, :dependent => :destroy, :inverse_of => :branch_record

  validates :name, :presence => true

  def to_param
    self.name
  end

  def kickoff_new_build_unless_currently_busy(ref)
    last_build = builds.last
    if last_build && !last_build.completed?
      last_build
    else
      builds.create_with(state: 'partitioning').find_or_create_by!(ref: ref)
    end
  end

  def abort_in_progress_builds_behind_build(current_build)
    builds.where(state: Build::IN_PROGRESS_STATES).readonly(false)
          .reject { |build| build.id >= current_build.id }
          .each { |build| build.abort! }
  end

  def most_recent_build
    @most_recent_build ||= builds.last
  end

  def last_completed_build
    @last_completed_build ||= builds.completed.last
  end

  # The fuzzy_limit is used to set a upper bound on the amount of time that the
  # sql query will take
  def timing_data_for_recent_builds(fuzzy_limit = 1000)
    id_cutoff = builds.maximum(:id).to_i - fuzzy_limit

    self.class.connection.execute(build_time_history_sql(id_cutoff))
  end

  private

  def build_time_history_sql(min_build_id)
    return <<-SQL
      SELECT build_parts.kind AS kind,
             SUBSTR(builds.ref, 1, 5) AS ref,
             IFNULL(FLOOR(ROUND(MAX(UNIX_TIMESTAMP(build_attempts.finished_at) - UNIX_TIMESTAMP(build_attempts.started_at)) / 60)), 0) AS max,
             IFNULL(FLOOR(ROUND(MAX(UNIX_TIMESTAMP(build_attempts.finished_at) - UNIX_TIMESTAMP(build_attempts.started_at)) / 60)) - FLOOR(ROUND(MIN(UNIX_TIMESTAMP(build_attempts.finished_at) - UNIX_TIMESTAMP(build_attempts.started_at)) / 60)), 0) AS min_diff,
             0 AS max_diff,
             builds.id,
             builds.state,
             builds.created_at
        FROM builds
   LEFT JOIN build_parts ON build_parts.build_id = builds.id
   LEFT JOIN build_attempts ON build_attempts.build_part_id = build_parts.id
       WHERE builds.branch_id = #{id}
         AND builds.id >= #{min_build_id}
         AND (build_attempts.id IS NULL OR build_attempts.id = (
               SELECT id
                 FROM build_attempts
                WHERE build_part_id = build_parts.id
             ORDER BY id DESC
                LIMIT 1
             ))
    GROUP BY builds.id, build_parts.kind, builds.state, builds.created_at
    SQL
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  caches_action :show, :build_time_history, cache_path: proc {
    load_repository_and_branch
    { :modified => [@branch.updated_at.to_i, @repository.updated_at.to_i].max }
  }

  caches_action :status_report, expires_in: 15.seconds

  # lists all convergence branches as well the 100 most recently active
  # branches
  def index
    load_repository
    @convergence_branches = @repository.branches.where(convergence: true)
    @recently_active_branches = @repository.branches.where(convergence: false).order('updated_at DESC').limit(100)
  end

  def show
    load_repository_and_branch
    @build = @branch.builds.build
    @builds = @branch.builds.includes(build_parts: :build_attempts).last(12)
    @current_build = @builds.last

    @build_parts = {}
    @builds.reverse_each do |build|
      build.build_parts.each do |build_part|
        key = [build_part.paths.first, build_part.kind, build_part.options['ruby']]
        (@build_parts[key] ||= {})[build] = build_part
      end
    end

    @branch = @branch.decorate

    respond_to do |format|
      format.html
      # Note: appending .rss to the end of the url will not return RSS format
      # due to the very permissive branch id constraint. Instead users will
      # have to specify a query param of format=rss to receive the RSS feed.
      format.rss { @builds = @builds.reverse } # most recent first
      format.json
    end
  end

  def request_new_build
    load_repository_and_branch

    ref = @repository.sha_for_branch(@branch.name)

    existing_build = @repository.build_for_commit(ref)

    if existing_build.present?
      flash[:warn] = "Did not find a new commit on the #{@branch.name} branch to build"
      redirect_to repository_branch_path(@repository, @branch)
    else
      build = @branch.builds.build(ref: ref, state: 'partitioning')

      if build.save
        flash[:message] = "New build started for #{build.ref} on #{@branch.name}"
        redirect_to repository_build_path(@repository, build)
      else
        flash[:error] = "Error adding build! #{build.errors.full_messages.to_sentence}"
        redirect_to repository_branch_path(@repository, @branch)
      end
    end
  end

  def health
    load_repository_and_branch
    initialize_stats_variables
    load_build_stats

    @builds = @branch.builds.includes(:build_parts => :build_attempts).last(params[:count] || 12)

    build_part_attempts = Hash.new(0)
    build_part_failures = Hash.new(0)
    failed_parts = {}
    @builds.each do |build|
      build.build_parts.each do |build_part|
        key = [build_part.paths.sort, build_part.kind]
        build_part.build_attempts.each do |build_attempt|
          if build_attempt.successful?
            build_part_attempts[key] = build_part_attempts[key] + 1
          elsif build_attempt.unsuccessful?
            build_part_attempts[key] = build_part_attempts[key] + 1
            build_part_failures[key] = build_part_failures[key] + 1
            failed_parts[key] = (failed_parts[key] || []) << build_part
          end
        end
      end
    end

    @part_climate = {}
    failed_parts.each do |key, parts|
      part_error_rate = (build_part_failures[key] * 100 / build_part_attempts[key])
      @part_climate[[part_error_rate, key]] = parts.uniq
    end

    @branch = @branch.decorate
  end

  def build_time_history
    load_repository_and_branch

    respond_to do |format|
      format.json do
        render json: @branch.decorate.build_time_history.to_json
      end
    end
  end

  # GET /XmlStatusReport.aspx
  #
  # This action returns the current build status for all of the convergence branches
  # in the system
  def status_report
    @branches = Branch.includes(:repository).where(convergence: true).decorate
  end

  def badge
    @repository || load_repository
    @branch ||= @repository.branches.where(name: params[:branch]).first!
    build = @branch.most_recent_build
    if build.succeeded?
      send_file('public/images/passing.svg', type: 'image/svg+xml', disposition: 'inline')
    elsif build.failed?
      send_file('public/images/failing.svg', type: 'image/svg+xml', disposition: 'inline')
    else # in progress
      send_file('public/images/pending.svg', type: 'image/svg+xml', disposition: 'inline')
    end
  end

  private

  def load_repository
    r_namespace, r_name = params[:repository_path].split('/')
    @repository = Repository.where(namespace: r_namespace, name: r_name).first!
  end

  def load_repository_and_branch
    @repository || load_repository
    @branch ||= @repository.branches.where(name: params[:id]).first!
  end

  # set the various stats variables to reasonable null values in case
  # the load_build_stats method short-circuits
  def initialize_stats_variables
    @days_since_first_build = 0
    @total_build_count = 0
    @total_failure_count = 0
    @total_pass_rate = '—'
    @last30_build_count = 0
    @last30_failure_count = 0
    @last30_pass_rate = '—'
    @last7_build_count = 0
    @last7_failure_count = 0
    @last7_pass_rate = '—'
  end

  def load_build_stats
    @first_built_date = @branch.builds.first.try(:created_at)
    return if @first_built_date.nil?

    @days_since_first_build = (Time.zone.today - @first_built_date.to_date).to_i

    @total_build_count = @branch.builds.count
    @total_failure_count = @branch.builds.where.not(state: 'succeeded').count
    @total_pass_rate = (@total_build_count - @total_failure_count) * 100 / @total_build_count

    @last30_build_count = @branch.builds.where('created_at >= ?', Time.zone.today - 30.days).count
    return if @last30_build_count.zero?
    @last30_failure_count = @last30_build_count - @branch.builds.where('state = "succeeded" AND created_at >= ?', Time.zone.today - 30.days).count
    @last30_pass_rate = (@last30_build_count - @last30_failure_count) * 100 / @last30_build_count

    @last7_build_count = @branch.builds.where('created_at >= ?', Time.zone.today - 7.days).count
    return if @last7_build_count.zero?
    @last7_failure_count = @last7_build_count - @branch.builds.where('state = "succeeded" AND created_at >= ?', Time.zone.today - 7.days).count
    @last7_pass_rate = (@last7_build_count - @last7_failure_count) * 100 / @last7_build_count
  end
end

app/views/branches/health.html.haml
= content_for :title, "Health of #{@branch.name} branch of #{@repository.name_with_namespace}"
= content_for :favicon do
  - if @current_build
    = favicon_link_tag image_path("#{@current_build.to_color}.png"), type: 'image/png'

- content_for :header do
  %ul.links
    %li= link_to("Settings", repository_edit_path(@repository), class: "info")
    %li= link_to("Branches", repository_branches_path(@repository))

- cache(@branch) do
  - rate = error_free_pass_rate(@builds)
  - avg_rebuilds = average_number_of_rebuilds(@builds)
  - median_seconds_to_success = median_elapsed_time(@builds)
  .performance
    - if median_seconds_to_success
      %div{title: "Median elapsed time for successful builds on #{@branch.name}"}
        %span.label Median time:
        %span.number #{seconds_to_minutes(median_seconds_to_success)} minutes

    - unless @builds.empty?
      %div{title: "Average number of build parts reattempted to get to a successful build", class: rebuild_count_css_class(avg_rebuilds)}
        %span.number= format("%0.1f", avg_rebuilds)
        %span.label rebuilds required on average

      %div{title: "Percentage of builds with all parts succeeding on the first try", class: pass_rate_css_class(rate)}
        %span.number= rate
        %span.label pass rate on first try

  .stats
    %h2.subheader Build statistics
    - if @first_built_date
      %p First build created on #{@first_built_date.strftime("%Y-%m-%d")}
    %table.build-stats
      %thead
        %tr
          %th
          %th Total
          %th Failures
          %th Pass Rate
      %tbody
        %tr
          %td All Time (#{@days_since_first_build} days)
          %td= @total_build_count
          %td= @total_failure_count
          %td #{@total_pass_rate}%
        %tr
          %td Past 30 days
          %td= @last30_build_count
          %td= @last30_failure_count
          %td #{@last30_pass_rate}%
        %tr
          %td Past 7 days
          %td= @last7_build_count
          %td= @last7_failure_count
          %td #{@last7_pass_rate}%

- if @part_climate.count > 0
  %h2.subheader #{@repository.name}/#{@branch.name} part failure stats over #{@builds.count} builds
  %table.project-part-info
    %thead
      %tr
        %th.right.whisker Rate
        %th Part Info
    - @part_climate.sort.reverse_each do |key, parts_with_failures|
      %tr
        %td.right #{key[0]}%
        %td= format_paths(parts_with_failures.first)
      %tr
        %td
        %td
          - parts_with_failures.each do |part|
            = link_to repository_build_part_path(@repository, part.build_instance, part) do
              %span.part-status{class: [part.status, "attempt-#{part.build_attempts.size}"]}
- else
  %h2.subheader #{@repository.name}/#{@branch.name} hasn't failed in #{@builds.count} builds

app/views/branches/index.html.haml
- content_for :header do
  %ul.links
    %li= link_to("Repositories", repositories_path)

.projects
  %ul
    - @convergence_branches.each do |branch|
      %li.build-info.bold
        = link_to(branch.name, repository_branch_path(branch.repository, branch))
    - @recently_active_branches.each do |branch|
      %li.build-info
        = link_to(branch.name, repository_branch_path(branch.repository, branch))

app/views/branches/show.html.haml
= content_for :title, "#{@repository.name} : #{@branch.name}"
= content_for :favicon do
  - if @current_build
    = favicon_link_tag image_path("#{@current_build.to_color}.png"), type: 'image/png'

- content_for :header do
  %ul.links
    %li= link_to("Settings", repository_edit_path(@repository), class: "info")
    %li= link_to("Branches", repository_branches_path(@repository))
  = form_for @build, url: request_new_build_repository_branch_path(@repository, @branch) do |f|
    - if @repository.enabled?
      = f.submit "Build", class: 'build-button'
    - else
      = f.submit "Build", class: 'build-button', disabled: 'true'

- cache(@branch) do
  %div.health.button= link_to('Health', health_repository_branch_path(@repository, @branch, 'count' => 12))
  - rate = error_free_pass_rate(@builds)
  - avg_rebuilds = average_number_of_rebuilds(@builds)
  - median_seconds_to_success = median_elapsed_time(@builds)
  .performance
    - if median_seconds_to_success
      %div{title: "Median elapsed time for successful builds on #{@branch.name}"}
        %span.label Median time:
        %span.number #{seconds_to_minutes(median_seconds_to_success)} minutes
    - else
      %div{title: "Median elapsed time for successful builds on #{@branch.name}"}
        %span.label Never built

    - unless @builds.empty?
      %div{title: "Average number of build parts reattempted to get to a successful build", class: rebuild_count_css_class(avg_rebuilds)}
        %span.number= format('%0.1f', avg_rebuilds)
        %span.label rebuilds required on average

      %div{title: "Percentage of builds with all parts succeeding on the first try", class: pass_rate_css_class(rate)}
        %span.number= rate
        %span.label completion rate on first try

%h2.subheader
  = @repository.namespace + '/' + @repository.name
  &ndash;
  = @branch.name

#plot

.select_commit
  %input{type: "text", id: "build_ref_input", placeholder: "Commit Revision"}
  %button{onClick: "goto_ref();"} Lookup Commit

= content_for :javascript do
  :javascript
    $(document).ready(Kochiku.graphBuildTimes("#{escape_javascript(@repository.to_param)}", "#{escape_javascript(@branch.name)}"));
    $(function() {
      var whisker = $('th.whisker');
      $('table')
        .on('mouseenter', '.whisker .part-status', function() {
          whisker.text($(this).data('ref'));
        })
        .on('mouseleave', '.whisker', function() {
          whisker.text('Previous');
        });
    });

    var goto_ref = function() {
      window.location.href = "//" + location.host + "/builds/" + $('#build_ref_input').val();
    };

- if @current_build
  %table.project-part-info
    %thead
      %tr
        %th.right.whisker Previous
        %th.status
          %code.build-status{class: @current_build.state}
            = link_to @current_build.ref[0, 5], repository_build_path(@repository, @current_build)
        - display_ruby_version = multiple_ruby_versions?(@current_build)
        - build_metadata_headers(@current_build, display_ruby_version).each do |header|
          %th{class: header.downcase.gsub(/\W+/, '-')}= header
        %th.type Type
        %th.right.time Elapsed
        %th.right.count Attempt
    - @build_parts.each do |_key, build_parts_by_build|
      - part = build_parts_by_build.values.first
      - build_part = build_parts_by_build[@current_build]
      - cache(part) do
        %tr{:id => dom_id(part)}
          %td.right.whisker
            - total_attempts = 0
            - @builds[0..-2].each do |previous_build|
              - previous_part = build_parts_by_build[previous_build]
              - if previous_part.present?
                - attempts = previous_part.build_attempts.size
                - total_attempts += attempts
                = link_to "/#{@repository.to_param}/builds/#{previous_build.to_param}/parts/#{previous_part.to_param}" do
                  %span.part-status{class: [previous_part.status, "attempt-#{attempts}"], title: pluralize(attempts, 'attempt'), data: { ref: previous_build.ref[0, 5] }}
              - else
                %span.part-status.attempt-0
          %td
            - if build_part
              %span.part-status{class: build_part.status}
                = link_to build_part.status.to_s.capitalize, "/#{@repository.to_param}/builds/#{@current_build.to_param}/parts/#{build_part.to_param}"
          - build_metadata_values(@current_build, part, display_ruby_version).each do |value|
            %td= value
          %td= part.kind.to_s
          %td.right.elapsed= build_part.elapsed_time ? duration_strftime(build_part.elapsed_time) : '' if build_part
          %td.right
            = build_part.build_attempts.size if build_part

- if @current_build
  = content_for :javascript do
    :javascript
      (function() {
        var startTimes = #{
          start_times = {}
          @current_build.build_parts.each { |part| start_times[dom_id(part)] = part.started_at if part.running? }
          start_times.to_json
        };
        var now = new Date();
        for(var partDomId in startTimes) {
          if(!startTimes.hasOwnProperty(partDomId)) {
            continue;
          }
          var startTime = new Date(Date.parse(startTimes[partDomId]));
          $('.project-part-info tbody').find('tr#' + partDomId + ' > .elapsed').text(
            Math.round((now-startTime)/60000) + ":" + ("00" + (Math.round((now-startTime)/1000)%60)).slice(-2));
        }
      })()

app/views/branches/show.json.erb
<%
  json_data = @branch.attributes
  json_data['recent_builds'] = @builds
%>
<%= json_data.to_json.html_safe %>