config/routes.rb
require 'resque/server'

Kochiku::Application.routes.draw do
  mount Resque::Server.new, :at => '/resque'

  if Rails.env.development?
    # https://github.com/rails/rails/pull/17896
    get '/rails/mailers' => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
  end

  root :to => "repositories#dashboard"

  get '/_status' => "status#available"

  # /repositories/1/build-ref?ref=master&sha=abc123
  resources :repositories, only: [:index, :create, :new, :update, :destroy] do
    member do
      post "build-ref", :action => 'build_ref', :as => 'build_ref'
    end
  end

  match '/XmlStatusReport.aspx', to: "branches#status_report", defaults: {:format => 'xml'}, via: :get
  match '/worker_health', to: "dashboards#build_history_by_worker", via: :get, as: :build_history_by_worker

  match 'builds/:id' => "builds#build_redirect", :via => :get, :as => :build_redirect, :id => /\d+/
  match 'builds/:id/status' => "builds#build_status", :via => :get, :as => :build_status, :id => /\d+/, :defaults => { :format => 'json' }
  match 'builds/:ref' => "builds#build_ref_redirect", :via => :get, :as => :build_ref_redirect
  match '/build_attempts/:build_attempt_id/build_artifacts' => "build_artifacts#create", :via => :post
  match '/build_attempts/:id/start' => "build_attempts#start", :via => :post
  match '/build_attempts/:id/finish' => "build_attempts#finish", :via => :post, :as => :finish_build_attempt
  # left here for backward compatibility in case if anyone uses it. /build_attempts/:id should be used instead.
  match '/build_attempts/:id/build_part' => "build_attempts#show", :via => :get, :as => :build_part_redirect
  match '/build_attempts/:id/stream_logs' => "build_attempts#stream_logs", :via => :get, :as => :stream_logs
  match '/build_attempts/:id/stream_logs_chunk' => "build_attempts#stream_logs_chunk", :via => :get, :as => :stream_logs_chunk
  match '/pull-request-builder' => "pull_requests#build", :via => :post, :as => :pull_request_build
  get 'badge/*repository_path', to: 'branches#badge'

  # Redirects for legacy urls
  get '/projects/:project_id/builds/:build_id', to: redirect('/builds/%{build_id}')

  resources :build_artifacts, :only => [:show]
  resources :builds, only: [:create]
  resources :build_attempts, only: [:show]

  scope path: "*repository_path", as: 'repository', constraints: { repository_path: /[^\/]+\/[^\/]+/ }, format: false do
    get 'edit', to: 'repositories#edit'

    resources :builds, only: [:show] do
      post 'toggle-merge-on-success', :action => "toggle_merge_on_success", :on => :member, :as => :toggle_merge_on_success
      patch 'abort', :action => "abort", :on => :member
      get 'status', :action => "build_status", :on => :member, :defaults => { :format => 'json' }
      post 'rebuild-failed-parts', :action => "rebuild_failed_parts", :on => :member, :as => :rebuild_failed_parts
      post 'retry-partitioning', :action => "retry_partitioning", :on => :member, :as => :retry_partitioning
      get 'modified_time', :action => "modified_time", :on => :member, :defaults => { :format => 'json' }
      get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      post 'resend-status', :action => "resend_status",  :on => :member, :defaults => { :format => 'json' }

      resources :build_parts, as: 'parts', path: 'parts', only: [:show] do
        post 'rebuild', on: :member
        get 'modified_time', action: "modified_time", on: :member, defaults: { format: 'json' }
        get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      end
    end

    # override branch id to allow branch name to contain both slashes and dots
    resources :branches, path: "", only: [:index, :show], constraints: { id: /.+/ } do
      member do
        post 'request-new-build', action: "request_new_build"
        get 'build-time-history', action: "build_time_history", defaults: { format: 'json' }
        get 'health', action: 'health'
      end
      get 'status-report', action: "status_report", on: :collection
    end
  end
end

app/models/repository.rb
require 'remote_server'

# This Repository class should only concern itself with persisting and acting on
# Repository records in the database. All non-database operations should go
# through the RemoteServer classes.
class Repository < ActiveRecord::Base
  has_many :branches, :dependent => :destroy
  has_many :convergence_branches, -> { where(convergence: true) }, class_name: "Branch"
  has_many :builds, through: :branches
  has_many :build_parts, through: :builds
  has_many :build_attempts, through: :build_parts
  validates :host, :name, :url, presence: true
  validates :name, uniqueness: { scope: :namespace, message: "^Namespace + Name combination already exists",
                                 case_sensitive: false }
  validates :timeout, numericality: { :only_integer => true }
  validates :timeout, inclusion: { in: 0..1440, message: 'The maximum timeout allowed is 1440 minutes' }
  validates :assume_lost_after, numericality: { :only_integer => true }, :allow_nil => true
  validates :url, uniqueness: true, allow_blank: true
  validate :validate_url_against_remote_servers

  def self.lookup_by_url(url)
    remote_server = RemoteServer.for_url(url)
    repository_namespace = remote_server.attributes.fetch(:repository_namespace)
    repository_name = remote_server.attributes.fetch(:repository_name)
    repository_host_and_aliases = remote_server.attributes.fetch(:possible_hosts)

    Repository.find_by(host: repository_host_and_aliases,
                       namespace: repository_namespace,
                       name: repository_name)
  end

  def self.lookup(host:, namespace:, name:)
    git_server_settings = Settings.git_server(host)

    Repository.find_by(host: [git_server_settings.host, *git_server_settings.aliases].compact,
                       namespace: namespace,
                       name: name)
  end

  # Setting a URL will extract values for host, namespace, and name. This
  # should not overwrite values for those attributes that were set in the same
  # session.
  def url=(value)
    # this column is deprecated; eventually url will just be a virtual attribute
    self[:url] = value

    return unless RemoteServer.parseable_url?(value)
    return unless RemoteServer.valid_git_host?(value)

    attrs_from_remote_server = RemoteServer.for_url(value).attributes
    self.host = attrs_from_remote_server[:host] unless host_changed?
    self.namespace = attrs_from_remote_server[:repository_namespace] unless namespace_changed?
    self.name = attrs_from_remote_server[:repository_name] unless name_changed?
  end

  def remote_server
    @remote_server ||= RemoteServer.for_url(url)
  end

  delegate :base_html_url, :base_api_url, :sha_for_branch, :url_for_fetching, :get_branch_url, :open_pull_request_url, to: :remote_server

  def promotion_refs
    on_green_update.split(",").map(&:strip).reject(&:blank?)
  end

  def interested_github_events
    event_types = ['pull_request']
    event_types << 'push' if run_ci
    event_types
  end

  def scm_type
    Settings.git_server(self.url).type
  end

  # Public: attempts to lookup a build for the commit under any of the
  # repository's branches. This is done as an optimization since the contents
  # of the commit are guaranteed to not have changed.
  #
  # Returns: Build AR object or nil
  def build_for_commit(sha)
    Build.joins(:branch_record).find_by(:ref => sha, 'branches.repository_id' => self.id)
  end

  # Public: looks across all of a repository's builds for one with the given
  # SHA. If one does not exist it creates one on the branch given
  #
  # sha    - String: git sha of the commit in question
  # branch - String or AR Branch: if an existing build is not found a new one will be created on this branch
  #
  # Returns: Build AR object
  def ensure_build_exists(sha, branch)
    build = build_for_commit(sha)
    unless build.present?
      build = branch.builds.create!(ref: sha, state: 'partitioning')
    end
    build
  end

  def name_with_namespace
    "#{namespace}/#{name}"
  end
  alias to_param name_with_namespace

  private

  def validate_url_against_remote_servers
    return unless url.present?

    if RemoteServer.parseable_url?(url)
      unless RemoteServer.valid_git_host?(url)
        errors.add(:url, "host is not in Kochiku's list of git servers")
      end
    else
      errors.add(:url, 'is not in a format supported by Kochiku')
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def create
    if params.fetch(:repository)[:url].blank?
      redirect_to new_repository_path, error: "Missing required value: Repository URL"
      return
    end

    @repository = Repository.new(repository_params)

    # persist the repository and then create initial Branch records for the
    # convergence branches
    if @repository.save && update_convergence_branches
      redirect_to repository_branches_path(@repository)
    else
      @current_convergence_branches = params.fetch(:convergence_branches, "").split(',')
      render template: 'repositories/new'
    end
  end

  def new
    @repository = Repository.new
    @repository.run_ci = true
    @current_convergence_branches = ['master']
  end

  def destroy
    ActiveRecord::Base.no_touching do
      Repository.destroy(params[:id])
    end
    redirect_to repositories_path
  end

  def update
    @repository = Repository.find(params[:id])

    if @repository.update_attributes(repository_params) && update_convergence_branches
      flash[:message] = "Settings updated."
      redirect_to repository_edit_url(@repository)
    else
      @current_convergence_branches = params.fetch(:convergence_branches, "").split(',')
      render template: 'repositories/edit'
    end
  end

  def edit
    r_namespace, r_name = params[:repository_path].split('/')
    @repository = Repository.where(namespace: r_namespace, name: r_name).first!

    @current_convergence_branches = @repository.branches.where(convergence: true).select(:name).collect(&:name)
  end

  def index
    @repositories = Repository.all
  end

  def dashboard
    @branches =
      Branch.joins(:repository)
            .includes(:repository)
            .where(name: 'master')
            .order('repositories.name')
            .decorate
  end

  # build_ref is intended to be used by the Stash webhooks plugin
  # https://marketplace.atlassian.com/plugins/com.atlassian.stash.plugin.stash-web-post-receive-hooks-plugin
  def build_ref
    repository = Repository.find(params[:id])

    # Query string parameters are provided for easy integrations, since it the
    # simplest to implement.
    changes = if params[:refChanges]
                params[:refChanges].map do |change|
                  [
                    change[:refId].gsub(/^refs\/heads\//, ''),
                    change[:toHash]
                  ]
                end
              else
                [params.values_at(:ref, :sha)]
              end

    result = changes.map do |ref, sha|
      ensure_build(repository, ref, sha)
    end

    render json: {
      builds: result.map { |build|
        {
          id:        build.id,
          build_url: repository_build_url(repository, build)
        }
      }
    }
  end

  def ensure_build(repository, branch_name, sha)
    branch = repository.branches.where(name: branch_name).first_or_create!

    build = repository.ensure_build_exists(sha, branch)
    branch.abort_in_progress_builds_behind_build(build) unless branch.convergence?

    build
  end

  private

  def repository_params
    params.require(:repository)
          .permit(:enabled, :url, :timeout, :build_pull_requests,
                  :run_ci, :on_green_update, :send_build_success_email,
                  :send_build_failure_email, :allows_kochiku_merges,
                  :email_on_first_failure, :send_merge_successful_email,
                  :assume_lost_after)
  end

  # update_convergence_branches is called by both create and update. This
  # method does more work than is necessary for create but it is used to avoid
  # duplicating code.
  def update_convergence_branches
    new_branch_names = params.fetch(:convergence_branches, "").split(',').map(&:strip)
    current_convergence_branches = @repository.branches.where(convergence: true).all
    current_branch_names = current_convergence_branches.collect(&:name)
    remove_convergence_from = current_branch_names - new_branch_names
    add_convergence_to = new_branch_names - current_branch_names

    remove_convergence_from.each do |name|
      current_convergence_branches.detect { |branch|
        branch.name == name
      }.update!(convergence: false)
    end

    add_convergence_to.each do |name|
      branch = @repository.branches.where(name: name).first_or_create!
      branch.update!(convergence: true)
    end
    true
  end
end

app/views/repositories/_form.html.haml
= form_for @repository, :url => form_url, :html => { :id => 'repository-form' } do |f|
  = f.error_messages
  %div
    %label{:for => "url"} Repository URL:
    = f.text_field :url, :placeholder => '', :autocapitalize => 'off', :autocorrect => 'off', :spellcheck => 'false'
  %div
    %label{:for => "convergence_branches"} Convergence Branches:
    = text_field_tag :convergence_branches, @current_convergence_branches.join(', '), placeholder: "master", autocapitalize: 'off', autocorrect: 'off', spellcheck: 'false'
  - if @repository.test_command.present?
    %div{title: 'Test command should now be specified in the kochiku.yml'}
      %label{:for => "test_command"} Test Command: (Deprecated)
      = f.text_field :test_command, :id => 'test_command', :disabled => true
  %div
    %label{:for => "timeout"} Timeout a build part after:
    = f.text_field :timeout, :id => "timeout", :class => "short"
    minutes
  %div
    %label{:for => "assume_lost_after"} Assume that a build has been lost if its still running after:
    = f.text_field :assume_lost_after, :id => "assume_lost_after", :class => "short"
    minutes
  %div
    %label{:for => "run_ci"} Trigger build on push to master:
    = f.check_box :run_ci, :id => "run_ci"
  %div
    %label{:for => "enabled"} Enable repository:
    = f.check_box :enabled, :id => "enabled"


  %fieldset
    %legend Pull Requests
    %div
      %label{:for => "build_pull_requests"} Build pull requests:
      = f.check_box :build_pull_requests, :id => "build_pull_requests"
    %div
      %label{:for => "allows_kochiku_merges"} Allow developers to request branches be merged into master on success:
      = f.check_box :allows_kochiku_merges, :id => "allows_kochiku_merges"

      - display_css = @repository.allows_kochiku_merges ? '' : 'display: none'
      %span{:id => 'branch-delete-warning', :style => display_css} Warning: Kochiku will delete the branch from Git after merging.
    %div
      %label{:for => "send_merge_successful_email"} Send email on automatic merge success:
      = f.check_box :send_merge_successful_email, :id => "send_merge_successful_email", :disabled => @repository.allows_kochiku_merges ? nil : true

  %fieldset
    %legend On a green build
    %div
      %label{:for => "on_green_update"} Update branches to last green commit:
      = f.text_field :on_green_update, :id => "on_green_update", :placeholder => "Comma separated list of branch names"
    %div
      %label{:for => "send_build_success_email"} Send email to contributers:
      = f.check_box :send_build_success_email, :id => "send_build_success_email"

  %fieldset
    %legend On a red build
    %div
      %label{:for => "send_build_failure_email"} Send email to build breakers:
      = f.check_box :send_build_failure_email, :id => "send_build_failure_email"
    %div
      %label{:for => "email_on_first_failure"} Email on first build part failure for branch builds:
      = f.check_box :email_on_first_failure, :id => "email_on_first_failure"

  = f.submit @repository.new_record? ? "Create" : "Update"

- unless @repository.new_record?
  = button_to "Delete", repository_path(@repository.id), method: :delete, form_class: "delete-form", class: "danger-button", data: {confirm: "This is a permanent destructive action, are you sure?"}

= content_for :javascript do
  :javascript
    $('#allows_kochiku_merges').change(function(){
      $('#branch-delete-warning').toggle($("#allows_kochiku_merges").is(':checked'));
      $('#send_merge_successful_email').prop("disabled", !$("#allows_kochiku_merges").is(':checked'));
    });
    $('#repository-form').submit(function(event) {
      // Manually update the hidden element generated by the Rails check_box helper.
      //
      // This workaround is neccessary for send_merge_successful_email to
      // maintain it's value when its input is is 'disabled'.
      $("input[name='repository[send_merge_successful_email]'][type='hidden']").val(
        $("input[name='repository[send_merge_successful_email]'][type='checkbox']").is(':checked')
      );
    });

app/views/repositories/dashboard.html.haml
- content_for :header do
  %ul.links
    %li= link_to("Repositories", repositories_path)

.projects.projects-grid
  - @branches.each do |branch|
    - cache(branch) do
      %div.ci-build-info{:class => "ci-#{branch.most_recent_build_state}"}
        %div.project-name
          = link_to(branch.repository.name, repository_branch_path(branch.repository, branch))
        - if branch.most_recent_build.try(:is_running?)
          %div.state{:class => "build-#{branch.most_recent_build_state}"}
            = branch.most_recent_build_state.to_s.capitalize
        - if branch.last_completed_build && branch.last_completed_build.finished_at
          %div.state
            Last built
            = timeago(branch.last_completed_build.finished_at)
        - else
          %div.state Never built
        - if branch.last_completed_build
          %div.state{:class => "build-#{branch.last_completed_build.state}"}
            = branch.last_completed_build.state.to_s.capitalize
            = "in " + distance_of_time_in_words(branch.last_build_duration) if branch.last_build_duration
        %div.project-link
          = link_to("all branches", repository_branches_path(branch.repository))

app/views/repositories/edit.html.haml
= render 'form', form_url: repository_url(@repository.id)

%br
%h3 Web Hooks
%p
  %strong Build SHA
  %br
  = link_to build_ref_repository_url(@repository.id, ref: 'master', sha: 'abc123')
  %br
  %em.hint
    POST to this URL from your source control system to trigger a build
    of the given branch/SHA.

app/views/repositories/index.html.haml
.repositories
  .new-repository-link
    = link_to("Add Repository", new_repository_path)

  %ul
    - @repositories.each do |repository|
      %li.build-info
        = link_to(repository.url, repository_edit_path(repository))

app/views/repositories/new.html.haml
= render 'form', form_url: repositories_url