config/routes.rb
require 'resque/server'

Kochiku::Application.routes.draw do
  mount Resque::Server.new, :at => '/resque'

  if Rails.env.development?
    # https://github.com/rails/rails/pull/17896
    get '/rails/mailers' => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
  end

  root :to => "repositories#dashboard"

  get '/_status' => "status#available"

  # /repositories/1/build-ref?ref=master&sha=abc123
  resources :repositories, only: [:index, :create, :new, :update, :destroy] do
    member do
      post "build-ref", :action => 'build_ref', :as => 'build_ref'
    end
  end

  match '/XmlStatusReport.aspx', to: "branches#status_report", defaults: {:format => 'xml'}, via: :get
  match '/worker_health', to: "dashboards#build_history_by_worker", via: :get, as: :build_history_by_worker

  match 'builds/:id' => "builds#build_redirect", :via => :get, :as => :build_redirect, :id => /\d+/
  match 'builds/:id/status' => "builds#build_status", :via => :get, :as => :build_status, :id => /\d+/, :defaults => { :format => 'json' }
  match 'builds/:ref' => "builds#build_ref_redirect", :via => :get, :as => :build_ref_redirect
  match '/build_attempts/:build_attempt_id/build_artifacts' => "build_artifacts#create", :via => :post
  match '/build_attempts/:id/start' => "build_attempts#start", :via => :post
  match '/build_attempts/:id/finish' => "build_attempts#finish", :via => :post, :as => :finish_build_attempt
  # left here for backward compatibility in case if anyone uses it. /build_attempts/:id should be used instead.
  match '/build_attempts/:id/build_part' => "build_attempts#show", :via => :get, :as => :build_part_redirect
  match '/build_attempts/:id/stream_logs' => "build_attempts#stream_logs", :via => :get, :as => :stream_logs
  match '/build_attempts/:id/stream_logs_chunk' => "build_attempts#stream_logs_chunk", :via => :get, :as => :stream_logs_chunk
  match '/pull-request-builder' => "pull_requests#build", :via => :post, :as => :pull_request_build
  get 'badge/*repository_path', to: 'branches#badge'

  # Redirects for legacy urls
  get '/projects/:project_id/builds/:build_id', to: redirect('/builds/%{build_id}')

  resources :build_artifacts, :only => [:show]
  resources :builds, only: [:create]
  resources :build_attempts, only: [:show]

  scope path: "*repository_path", as: 'repository', constraints: { repository_path: /[^\/]+\/[^\/]+/ }, format: false do
    get 'edit', to: 'repositories#edit'

    resources :builds, only: [:show] do
      post 'toggle-merge-on-success', :action => "toggle_merge_on_success", :on => :member, :as => :toggle_merge_on_success
      patch 'abort', :action => "abort", :on => :member
      get 'status', :action => "build_status", :on => :member, :defaults => { :format => 'json' }
      post 'rebuild-failed-parts', :action => "rebuild_failed_parts", :on => :member, :as => :rebuild_failed_parts
      post 'retry-partitioning', :action => "retry_partitioning", :on => :member, :as => :retry_partitioning
      get 'modified_time', :action => "modified_time", :on => :member, :defaults => { :format => 'json' }
      get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      post 'resend-status', :action => "resend_status",  :on => :member, :defaults => { :format => 'json' }

      resources :build_parts, as: 'parts', path: 'parts', only: [:show] do
        post 'rebuild', on: :member
        get 'modified_time', action: "modified_time", on: :member, defaults: { format: 'json' }
        get 'refresh_build_part_info', :action => "refresh_build_part_info", :on => :member, :defaults => { :format => 'json' }
      end
    end

    # override branch id to allow branch name to contain both slashes and dots
    resources :branches, path: "", only: [:index, :show], constraints: { id: /.+/ } do
      member do
        post 'request-new-build', action: "request_new_build"
        get 'build-time-history', action: "build_time_history", defaults: { format: 'json' }
        get 'health', action: 'health'
      end
      get 'status-report', action: "status_report", on: :collection
    end
  end
end

app/controllers/builds_controller.rb
require 'git_repo'

class BuildsController < ApplicationController
  before_action :load_repository, :only => [:show, :retry_partitioning, :rebuild_failed_parts, :request_build, :abort, :toggle_merge_on_success, :build_status, :modified_time, :refresh_build_part_info, :resend_status]
  before_action only: [:show, :refresh_build_part_info] do
    @build = Build.includes(build_parts: :build_attempts)
                  .joins(:branch_record).where('branches.repository_id' => @repository.id)
                  .find(params[:id])
    calculate_build_parts_position(@build)
    format_build_parts_position
  end

  include BuildAttemptsQueuePosition

  caches_action :show, cache_path: proc {
    updated_at = Build.select(:updated_at).find(params[:id]).updated_at
    {
      build_modified: [updated_at.to_i, @repository.updated_at.to_i].max,
      queue_position: Digest::SHA1.hexdigest(@build_attempts_rank.values.join(','))
    }
  }

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @build, include: { build_parts: { methods: [:status] } } }
      format.png do
        # See http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21
        headers['Expires'] = CGI.rfc1123_date(Time.now.utc)

        send_data(@build.to_png, :type => 'image/png', :disposition => 'inline')
      end
    end
  end

  # Public: Kickoff a build from the kochiku CLI script
  #
  # repo_url         - The remote url for the git repository
  # git_sha          - (optional) the SHA of the specific git commit the user is requesting to build
  # git_branch       - String name of the git branch to perform the build of. If
  #                    'git_sha' is not specified then it will use HEAD of the git branch.
  # merge_on_success - Bool. Request kochiku automatically merge the branch if the build succeeds.
  #
  def create
    merge_on_success = (params[:merge_on_success] || false)
    repository = Repository.lookup_by_url(params[:repo_url])
    unless repository
      raise ActiveRecord::RecordNotFound, "Repository for #{params[:repo_url]} not found"
    end

    if params[:git_sha].present?
      build = repository.build_for_commit(params[:git_sha])
      if build
        head :ok, :location => repository_build_url(repository, build)
        return
      end
    end

    branch = repository.branches.where(name: params[:git_branch]).first_or_create!

    ref_to_build = if params[:git_sha].present?
                     params[:git_sha]
                   else
                     repository.sha_for_branch(branch.name)
                   end

    build = branch.builds.build(ref: ref_to_build, state: 'partitioning', merge_on_success: merge_on_success)

    if build.save
      head :ok, :location => repository_build_url(repository, build)
    else
      render :plain => build.errors.full_messages.join('\n'), :status => :unprocessable_entity
    end
  end

  def retry_partitioning
    @build = Build.joins(:branch_record).where('branches.repository_id' => @repository.id).find(params[:id])

    # This means there was an error with the partitioning job; redo it
    if @build.build_parts.empty?
      @build.update_attributes! :state => 'partitioning', :error_details => nil
      @build.enqueue_partitioning_job
    end

    redirect_to [@repository, @build]
  end

  def rebuild_failed_parts
    @build = Build.includes(build_parts: :build_attempts)
                  .joins(:branch_record).where('branches.repository_id' => @repository.id)
                  .find(params[:id])
    @build.build_parts.failed_errored_or_aborted.each do |part|
      # There is an exceptional case in Kochiku where a build part's prior attempt may have
      # passed but the latest attempt failed. We do not want to rebuild those parts.
      part.rebuild! if part.unsuccessful?
    end
    @build.update_attributes! state: 'running'

    redirect_to [@repository, @build]
  end

  def abort
    @build = Build.joins(:branch_record).where('branches.repository_id' => @repository.id).find(params[:id])
    @build.abort!
    redirect_to repository_build_path(@repository, @build)
  end

  def toggle_merge_on_success
    @build = Build.joins(:branch_record).where('branches.repository_id' => @repository.id).find(params[:id])
    @build.update_attributes!(:merge_on_success => params[:merge_on_success])
    redirect_to repository_build_path(@repository, @build)
  end

  def build_status
    @build = @repository ? @repository.builds.find(params[:id]) : Build.find(params[:id])

    respond_to do |format|
      format.json do
        render :json => @build
      end
    end
  end

  def modified_time
    updated_at = Build.joins(:branch_record).where('branches.repository_id' => @repository.id)
                      .find(params[:id]).updated_at
    respond_to do |format|
      format.json do
        render :json => updated_at
      end
    end
  end

  def resend_status
    @build = Build.joins(:branch_record).where('branches.repository_id' => @repository.id).find(params[:id])
    BuildStateUpdateJob.enqueue(@build.id)
    redirect_to repository_build_path(@repository, @build)
  end

  def refresh_build_part_info
    updates = []
    last_modified = Time.zone.at(params[:modified_time].to_i / 1000.0)
    if @build.completed?
      updates << { state: @build.state }
    else
      updatd_parts = @build.build_parts.where("updated_at > ? OR id in (?)", last_modified, @build_parts_position.keys)
      updatd_parts.each do |part|
        html = ApplicationController.render(partial: 'builds/build_parts', locals: { part: part.decorate,
                                                                                     build: @build,
                                                                                     build_parts_position: @build_parts_position,
                                                                                     repository: @repository })
        updates << {id: part.id, content: html, state: @build.state}
      end
    end
    respond_to do |format|
      format.json do
        render :json => updates
      end
    end
  end

  def build_redirect
    build_instance = Build.find(params[:id])
    redirect_to repository_build_path(build_instance.repository, build_instance)
  end

  def build_ref_redirect
    # search prefix so that entire git ref does not have to be provided.
    build_instance = Build.where("ref LIKE ?", "#{params[:ref]}%").first
    redirect_to repository_build_path(build_instance.repository, build_instance)
  end

  private

  def load_repository
    if params[:repository_path]
      r_namespace, r_name = params[:repository_path].split('/')
      @repository = Repository.where(namespace: r_namespace, name: r_name).first!
    end
  end

  def format_build_parts_position
    @build_parts_position = {}
    @build_attempts_rank&.each do |build_attempt_id, position|
      next if position.nil?
      build_part_id = BuildAttempt.find(build_attempt_id).build_part.id
      if @build_parts_position[build_part_id].nil?
        @build_parts_position[build_part_id] = position
      elsif @build_parts_position[build_part_id] > position
        @build_parts_position[build_part_id] = position
      end
    end
  end
end

app/helpers/build_helper.rb
module BuildHelper
  def build_metadata_headers(build, display_ruby_version)
    headers = []
    headers << "Ruby Version" if display_ruby_version

    if is_a_build_with_one_part?(build)
      headers << "Target"
    else
      headers << "Paths"
    end
    headers
  end

  def build_metadata_values(build, build_part, display_ruby_version)
    values = []
    values << build_part.options["ruby"] if display_ruby_version
    values << format_paths(build_part)
    values
  end

  def format_paths(build_part)
    if build_part.options['total_workers'] && build_part.options['worker_chunk']
      build_part.paths.first + " - Chunk #{build_part.options['worker_chunk']} of #{build_part.options['total_workers']}"
    elsif build_part.paths.size == 1
      if build_part.paths.first == "/dev/null"
        build_part.kind
      else
        build_part.paths.first
      end
    else
      first, *rest = build_part.paths
      first = first.sub(/([^\/]+)/, '<b class="root">\1</b>')
      paths = [first, rest].join(', ')
      "#{build_part.paths.length} <span class=\"paths\" title=\"#{build_part.paths.join(', ')}\">(#{paths})</span>".html_safe
    end
  end

  def multiple_ruby_versions?(build)
    build.build_parts.map { |bp| bp.options['ruby'] }.compact.uniq.size > 1
  end

  def is_a_build_with_one_part?(build)
    build.build_parts.none? { |build_part| build_part.paths.size > 1 }
  end

  def eligible_for_merge_on_success?(build)
    !build.succeeded? && !build.branch_record.convergence? && build.repository.allows_kochiku_merges?
  end
end

app/views/builds/_build.html.haml
.build
  %a.build-wrapper{:href => repository_build_path(build.repository, build)}
    .build-info
      .ref= build.ref
    %h3.build-id{:class => build.state}= build.id
    .times
      .time-started
        Started at
        = time_for(build.created_at, "%m/%d %I:%M%P")
      .time-elapsed
        - if build.completed?
          Built in
          %strong
            = duration_strftime(build.elapsed_time, "%Hh %Mm %Ss")

  .build-state
    %span.info
      %span.state{:class => 'build-' + build.state.to_s}= build.state.to_s.capitalize
      on
      %span.queue= build.queue.to_s.capitalize
    - if build.branch_record.convergence?
      %a.info{:href => show_link_to_compare(build, build.previous_successful_build.try(:ref), build.ref), :title => 'show changes since last green build'}
        Compare to last green build
    - elsif build.succeeded?
      %a.info{:href => show_link_to_create_pull_request(build), :title => 'create a pull request against master'}
        Create pull request
    - if build.on_success_script_log_file.present?
      = link_to File.basename(build.on_success_script_log_file.to_s), build.on_success_script_log_file.url, :class => :info
    %a.info.last{:href => show_link_to_commit(build.repository, build.ref)}
      Show HEAD commit

  .parts= render build.build_parts

app/views/builds/_build_parts.html.haml
- display_ruby_version = multiple_ruby_versions?(build)
%tr{:"data-id" => part.id}
  %td.right= link_to(part.id, repository_build_part_path(build.repository, build, part))
  %td
    %span.part-status{:class => part.status}
      - text = part.status.to_s.capitalize
      - if part.status == 'running' && part.last_attempt.log_streamer_port.present?
        = link_to(text, stream_logs_path(part.last_attempt.id))
      - elsif (artifact = part.most_recent_stdout_artifact)
        = link_to(text, artifact, :title => 'Last completed stdout.log')
      - else
        = text
  - position = build_parts_position[part.id]
  - if position.present?
    %td{:class => 'queue-position-value'}
      = position
  - else
    %td
  - build_metadata_values(build, part, display_ruby_version).each do |value|
    %td= value
  %td= part.kind.to_s
  %td.right
    - builder = part.last_attempt.try(:builder)
    = builder ? builder.sub(".#{Settings.domain_name}", '') : "pending"
  %td.right.elapsed= part.elapsed_time ? duration_strftime(part.elapsed_time) : "pending"
  %td.right= part.build_attempts.size
  %td.right
    - if part.unsuccessful? && repository.enabled?
      = link_to("Rebuild", rebuild_repository_build_part_path(build.repository, build, part), :method => :post)

app/views/builds/show.html.haml
= content_for :title do
  = @build.ref[0, 7]
  &ndash;
  = @build.repository.name
= content_for :favicon do
  = favicon_link_tag image_path("#{@build.to_color}.png"), :type => 'image/png'

%h2.subheader
  = @build.repository.name
  &ndash;
  = link_to(@build.branch_record.name, repository_branch_path(@build.repository, @build.branch_record))
  &ndash;
  %code.build-status{class: @build.state, title: @build.ref}
    = @build.ref[0, 7]
  %a.info{:href => show_link_to_commit(@build.repository, @build.ref)}
    Show
  - if @build.branch_record.convergence?
    %a.info{:href => show_link_to_compare(@build, @build.previous_successful_build.try(:ref), @build.ref), :title => 'show changes since last green build'}
      Compare to last green build

  .actions
    - if @build.succeeded?
      = button_to "Sync status to #{@build.repository.scm_type}", resend_status_repository_build_path(@build.repository, @build), :method => :post
    - if @build.repository.allows_kochiku_merges?
      %form{action: toggle_merge_on_success_repository_build_path(@build.repository, @build), method: :post}
        %label
          = check_box_tag :merge_on_success, true, @build.merge_on_success_enabled?, disabled: !eligible_for_merge_on_success?(@build), onchange: 'this.form.submit()'
          Merge on Success

    %label
      = check_box_tag :refresh, true, @build.is_running?
      Refresh

.build-info.build-info-subheader
  - if @build.succeeded? && !@build.branch_record.convergence?
    %a.info{:href => show_link_to_create_pull_request(@build), :title => 'create a pull request against master'}
      Create pull request
  %span.info
    Created
    = timeago(@build.created_at)
  %span.info
    Updated
    = timeago(@build.updated_at, :id => "time-since-update")
  - if @build.completed?
    %span.info
      Built in #{duration_strftime(@build.elapsed_time, "%Hh %Mm %Ss")}
  - if @build.completed? && @build.failed? && @build.build_parts.present?
    %span.info
      #{@build.build_parts.failed.count} out of #{@build.build_parts.count} build parts failed
  - if @build.is_running?
    %span.info
      = button_to "Abort Build", abort_repository_build_path(@build.repository, @build), method: :patch, class: "abort-build"
  - if @repository.enabled? && (@build.failed? || @build.aborted?)
    %span.info
      - if @build.build_parts.empty? || !@build.error_details.empty?
        = button_to "Retry Partitioning", retry_partitioning_repository_build_path(@build.repository, @build), :method => :post, :form_class => "retry-partitioning"
      - else
        = button_to "Rebuild failed parts", rebuild_failed_parts_repository_build_path(@build.repository, @build), :method => :post, :form_class => "rebuild-parts"

- if @build.error_details.present?
  .build-error
    %h2 Build error
    %pre= [@build.error_details[:message], @build.error_details[:backtrace]].join("\n")
- if @build.succeeded? && @build.build_parts.count == 0
  .build-empty
    %h2 Build Empty
    %span.info
      Partitioner did not return any work for this build.
%table.build-summary#build-summary
  %thead
    %tr
      %th.right.id Part
      %th.status Status
      %th.queue-position Position
      - display_ruby_version = multiple_ruby_versions?(@build)
      - build_metadata_headers(@build, display_ruby_version).each do |header|
        %th{class: header.downcase.gsub(/\W+/, '-')}= header
      %th.type Type
      %th.right.worker Worker
      %th.right.time Elapsed Time
      %th.right.count Attempt
      %th.right.actions Actions
  %tbody
    - @build.build_parts.decorate.each do |part|
      = render partial: 'builds/build_parts', locals: {part: part, build: @build, build_parts_position: @build_parts_position, repository: @repository}

- if @build.on_success_script_log_file.url
  = link_to(File.basename(@build.on_success_script_log_file.path), @build.on_success_script_log_file.url)
= content_for :javascript do
  :javascript
    if ($('#build-summary tbody tr').length > 0) {
      $('#build-summary').tablesorter({ sortList: [ [1, 0] ] });
      StartTimes = #{
        # rubocop:disable Style/IndentationConsistency
        start_times = {}
        @build.build_parts.each { |part| start_times[part.id] = part.started_at }
        start_times.to_json
      };
    }

    if ( "Notification" in window && Notification.permission == "default") {
      Notification.requestPermission();
    }

    Kochiku.buildInfo = {table: '.build-summary tbody', renderTime: Date.parse(#{raw @build.updated_at.to_json}), state: "#{@build.state}"};
    Kochiku.buildInfo.id = #{@build.id};
    Kochiku.buildInfo.branch = "#{@build.branch_record.name}";
    Kochiku.buildInfo.repo = "#{@build.repository.name}";

    Kochiku.terminalStates = #{raw Build::TERMINAL_STATES};
    Kochiku.delayedRefresh(Kochiku.buildInfo);
    Kochiku.doneMessage = "Build on "

    $('abbr.timeago').click(function() {
      // swap the relative time with the absolute time
      var originalText = $(this).text();
      $(this).text($(this).attr('title'));
      $(this).attr('title', originalText);
    });